Add custom VPC support in GCP
submariner-io/cloud-prepare pull request #1060
Opened 2024-12-06 19:57 UTC by aswinsuryan

Add custom VPC support in GCP

2025-01-07 13:11 UTC, tpantelis requested changes

2025-01-07 13:11 UTC, tpantelis commented on pkg/gcp/gcp.go
> +func NewCloud(info *CloudInfo) api.Cloud {
I assume you changed this to a pointer to avoid a linter error re: the struct size but it's preferable to pass by value here since `info` is mutated. Ignore the linter error with `//nolint`...

2025-01-08 02:02 UTC, tpantelis requested changes

2025-01-08 02:02 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +	*CloudInfo
```suggestion
	CloudInfo
```

2025-01-08 02:02 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +func NewOcpGatewayDeployer(info *CloudInfo, msDeployer ocp.MachineSetDeployer, instanceType, image string,
```suggestion
//nolint: gocritic // Ignore 'hugeParam' - pass by value for CloudInfo is intentional
func NewOcpGatewayDeployer(info CloudInfo, msDeployer ocp.MachineSetDeployer, instanceType, image string,
```

2025-01-08 04:17 UTC, aswinsuryan commented on pkg/gcp/ocpgwdeployer.go
> +	*CloudInfo
Done

2025-01-08 04:17 UTC, aswinsuryan commented on pkg/gcp/ocpgwdeployer.go
> +func NewOcpGatewayDeployer(info *CloudInfo, msDeployer ocp.MachineSetDeployer, instanceType, image string,
Done.

2025-01-08 04:17 UTC, aswinsuryan commented on pkg/gcp/gcp.go
> +func NewCloud(info *CloudInfo) api.Cloud {
Done,

2025-01-08 13:47 UTC, tpantelis approved these changes

2025-01-08 13:47 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +	}
No need to make another copy of 'info'.

```suggestion
	if info.VpcName == "" {
		info.VpcName = info.InfraID + "-network"
	}

	if info.PublicSubnetName == "" {
		info.PublicSubnetName = info.InfraID + "-worker-subnet"
	}
```

2025-01-08 13:48 UTC, tpantelis requested changes
Didn't mean to approve yet.

2025-01-09 02:59 UTC, aswinsuryan commented on pkg/gcp/ocpgwdeployer.go
> +	}
Done.

2025-01-09 19:57 UTC, tpantelis approved these changes

2025-01-21 14:28 UTC, vthapar approved these changes

2025-01-21 15:22 UTC, merged