Basic code to deploy Azure gateways
submariner-io/cloud-prepare pull request #204
Opened 2022-02-27 14:18 UTC by mkolesnik

This is a basic deployer of Azure gateway using MachineSet, it will be
further extended.

Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

2022-02-28 09:24 UTC, Jaanki requested changes

2022-02-28 09:24 UTC, Jaanki commented on pkg/azure/gw-machineset.go
> +  name: {{.InfraID}}-submariner-gw-{{.Region}}{{.AZ}}
Do we want to have such long name?

2022-02-28 09:24 UTC, Jaanki commented on pkg/azure/gw-machineset.go
> +          networkResourceGroup: {{.InfraID}}-rg
```suggestion
          networkResourceGroup: {{.BaseGroupName}}
```
BaseGroupName is part of azureCloud https://github.com/submariner-io/cloud-prepare/pull/203/files#diff-f2027c3046b53bdf075254bbf73d790797640745c6d58bff13b71992570287feR38

2022-02-28 09:24 UTC, Jaanki commented on pkg/azure/gw-machineset.go
> +          networkResourceGroup: {{.InfraID}}-rg
Applies everywhere.

2022-02-28 09:24 UTC, Jaanki commented on pkg/azure/gw-machineset.go
> +var machineSetYAML = `apiVersion: machine.openshift.io/v1beta1
you can use `go:embed` directive and then read it as string/file. See for eg  https://github.com/submariner-io/submariner-operator/blob/devel/pkg/subctl/cmd/gather/summary.go#L40

2022-05-03 13:08 UTC, dfarrell07 commented
@aswinsuryan will work on this, but will likely create a fresh PR. Closing for now.

2022-05-03 13:08 UTC, closed without merging