Fix SG assocation with dedicated gw node in rhos
submariner-io/cloud-prepare pull request #228
Opened 2022-03-17 17:06 UTC by aswinsuryan

Signed-off-by: Aswin Suryanarayanan <aswinsuryan@gmail.com>

2022-03-18 13:51 UTC, tpantelis commented on pkg/rhos/ocpgwdeployer.go
> +		return errors.Wrap(err, fmt.Sprintf("failed to list k8s nodes in project %q", d.projectID))
```suggestion
		return errors.Wrapf(err, "failed to list k8s nodes in project %q", d.projectID)
```

2022-03-18 15:03 UTC, tpantelis approved these changes

2022-03-18 15:06 UTC, vthapar requested changes

2022-03-18 15:06 UTC, vthapar commented on pkg/rhos/ocpgwdeployer.go
> +		err = d.removeGWFirewallRules(groupName, gwNodes[i].Name, computeClient)
```suggestion
		err = d.removeFirewallRulesFromGW(groupName, gwNodes[i].Name, computeClient)
```
Current name seems to suggest we're deleting the SG itself, while we're just removing association from gw node.

2022-03-19 14:17 UTC, vthapar approved these changes

2022-03-21 13:28 UTC, skitt approved these changes

2022-03-21 19:41 UTC, merged