Add support to tag existing node as g/w node
submariner-io/cloud-prepare pull request #291
Opened 2022-06-04 00:04 UTC by aswinsuryan

*  Add support to tag an existing node as g/w node
*  Open the required ports to enable g/w traffic
*  Removes the security groups and removes the tag in cleanup.

Signed-off-by: Aswin Suryanarayanan <aswinsuryan@gmail.com>

2022-06-06 14:08 UTC, tpantelis requested changes

2022-06-06 14:08 UTC, tpantelis commented on pkg/azure/ocpgwdeployer.go
> +		}
This should be outside the loop.

2022-06-06 14:08 UTC, tpantelis commented on pkg/azure/ocpgwdeployer.go
>  	if gatewayNodesToDeploy != 0 {
It seems this applies to the `dedicatedGWNode` case and thus should be after L124.

2022-06-13 14:18 UTC, tpantelis approved these changes

2022-06-13 19:52 UTC, dfarrell07 commented on pkg/azure/cloud_info.go
> +		return errors.Wrapf(err, "adding  security group %q and public IP %q to interface %q failed", *nwSecurityGroup.Name,
```suggestion
		return errors.Wrapf(err, "adding security group %q and public IP %q to interface %q failed", *nwSecurityGroup.Name,
```

2022-06-13 19:52 UTC, dfarrell07 commented on pkg/azure/cloud_info.go
> +		return errors.Wrapf(err, "updating  interface  %q failed", *nwInterface.Name)
```suggestion
		return errors.Wrapf(err, "updating interface %q failed", *nwInterface.Name)
```

2022-06-13 19:52 UTC, dfarrell07 commented on pkg/azure/cloud_info.go
> +	return errors.Wrapf(err, "waiting for the g/w interface  %q to be updated failed", interfaceName)
```suggestion
	return errors.Wrapf(err, "waiting for the g/w interface %q to be updated failed", interfaceName)
```

2022-06-14 00:28 UTC, dfarrell07 approved these changes

2022-06-14 00:33 UTC, tpantelis commented
@sridhargaddam Can you review?

2022-06-14 15:28 UTC, merged