Add load balancer option to GW api
submariner-io/cloud-prepare pull request #386
Opened 2022-09-11 14:27 UTC by yboaron

Signed-off-by: Yossi Boaron <yboaron@redhat.com>

2022-09-12 14:29 UTC, tpantelis requested changes

2022-09-12 14:29 UTC, tpantelis commented on pkg/api/api.go
> +	UseLB bool
```suggestion
	UseLoadBalancer bool
```

2022-09-12 15:34 UTC, tpantelis approved these changes

2022-09-13 18:30 UTC, dfarrell07 approved these changes

2022-09-18 11:59 UTC, merged