Add branch check GHA
submariner-io/cloud-prepare pull request #9
Opened 2021-04-23 12:36 UTC by tpantelis

2021-04-23 17:09 UTC, dfarrell07 approved these changes

2021-04-26 07:24 UTC, mangelajo requested changes
There is another version we have that also matches to release-xxxx. We should use the other one.

2021-04-26 11:37 UTC, tpantelis commented
> There is another version we have that also matches to release-xxxx. We should use the other one.

I copied this from the latest `submariner` project. It's also the same in the other projects except `submariner-operator` which has no such job.

2021-04-28 08:36 UTC, mkolesnik approved these changes

2021-04-28 13:03 UTC, mangelajo approved these changes

2021-04-28 13:03 UTC, merged