GCP support for deploying dedicated Gateway nodes
submariner-io/cloud-prepare pull request #92
Opened 2021-08-26 14:34 UTC by sridhargaddam

This PR implements the following
1. Supports deploying new Gateway nodes using the OCP machineset API
2. Cleanup of any existing gateway nodes and firewall rules
3. Fixes the public-firewall-rules to be applied only to gateway nodes

Fixes issue: https://github.com/submariner-io/cloud-prepare/issues/91
Signed-Off-by: Sridhar Gaddam <sgaddam@redhat.com>

2021-08-26 15:38 UTC, tpantelis requested changes

2021-08-26 15:38 UTC, tpantelis commented on pkg/gcp/client/client.go
> +	return resp, nil
```suggestion
	return g.computeClient.Instances.Get(g.projectID, zone, instance).Context(context.TODO()).Do()
```

2021-08-26 15:38 UTC, tpantelis commented on pkg/gcp/client/client.go
> +	return resp, nil
```suggestion
	return g.computeClient.Instances.List(g.projectID, zone).Context(context.TODO()).Do()
```

2021-08-26 15:38 UTC, tpantelis commented on pkg/gcp/client/client.go
> +	return resp, nil
```suggestion
	return g.computeClient.Zones.List(g.projectID).Context(context.TODO()).Do()
```

2021-08-26 15:38 UTC, tpantelis commented on pkg/gcp/client/client.go
> +	return false, nil
```suggestion
	return len(networkInterface.AccessConfigs) > 0, nil
```

2021-08-26 15:38 UTC, tpantelis commented on pkg/gcp/client/client.go
> +	return nil
```suggestion
	_, err := g.computeClient.Instances.AddAccessConfig(
		g.projectID, zone, instance.Name, networkInterface.Name, &compute.AccessConfig{}).
		Context(context.TODO()).Do()
	return err
```

2021-08-26 15:38 UTC, tpantelis commented on pkg/gcp/client/client.go
> +	return nil
```suggestion
	_, err := g.computeClient.Instances.DeleteAccessConfig(
		g.projectID, zone, instance.Name, "External NAT", networkInterface.Name).
		Context(context.TODO()).Do()
		
	return err
```

2021-08-26 15:38 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +		return fmt.Errorf("failed to list the zones in the project %q. %v", d.gcp.projectID, err)
You augment the return error with additional context - perhaps we should do the same with the `reporter`? Applies to other places as well

```suggestion
		return reportFailure(reporter, err, "failed to list the zones in the project %q", d.gcp.projectID)
		
	...
	func reportFailure(reporter api.Reporter, failure error, format string, args ...string) {
	    err  := errors.WithMessagef(failure, format, args)
	    reporter.Failed(err)
	    
	    return err
	}
```

2021-08-26 15:38 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +			err := d.deployGateway(zone.Name)
We use criteria on L84 and L101 above to ignore zones when determining if a zone has a current GW instance. But we don't use that same criteria here when selecting a zone on which to deploy nor do we ensure we deploy on a new zone, ie one we haven't already deployed on. Unless I'm missing something or my understanding of the code and concepts is incorrect....

2021-08-26 15:38 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +		}
So what if `gatewayNodesToDeploy` doesn't reach 0 and we end up here. That would mean we didn't find enough zones to satisfy the requested # of gateways. Should we return an error and/or report it?

2021-08-26 15:38 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +
What if `len(currentGWInstanceList) > input.Gateways`?  Should we undeploy gateways to match the request?

2021-08-26 15:38 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +		if region != d.gcp.region {
L84 above checks `zone.Region` as is which differs with L236 here. Shouldn't they behave the same?

2021-08-26 15:38 UTC, tpantelis commented on pkg/ocp/machinesets.go
> +	// TODO: After implementing a ListAll method in admiral, modify this code accordingly.
Where would this method go?

2021-08-26 17:26 UTC, sridhargaddam reviewed
Thanks for reviewing the PR @tpantelis

2021-08-26 17:26 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +			err := d.deployGateway(zone.Name)
Thats true. Basically, the idea is that the cloud-prepare API should be idempotent and if user calls with the same arguments any number of times the result should be the same. Currently, we do not have a use-case where users will try to increase/decrease the number of Gateways in a subsequent call. If you think I should also check the zone, I can do it in a subsequent PR. Hope its fine with you.

2021-08-26 17:26 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +		}
Added a check

2021-08-26 17:26 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +
Currently we do not have a use-case to reduce gateway count (except for cleanup). If there is any such requirement in future, we can look into it.

2021-08-26 17:26 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +		if region != d.gcp.region {
Good catch @tpantelis. You are just awesome.

2021-08-26 17:26 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +		if region != d.gcp.region {
Good catch @tpantelis. You are just awesome.

2021-08-26 17:26 UTC, sridhargaddam commented on pkg/ocp/machinesets.go
> +	// TODO: After implementing a ListAll method in admiral, modify this code accordingly.
In admiral/pkg/resource/interface.go, interface methods do not include ListAll

2021-08-26 18:20 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +			err := d.deployGateway(zone.Name)
> Thats true. Basically, the idea is that the cloud-prepare API should be idempotent and if user calls with the same arguments any number of times the result should be the same. 

Right and that's handled on line L110 above.

> Currently, we do not have a use-case where users will try to increase/decrease the number of Gateways in a subsequent call.

hmm... but this is handling the increase case. If there's no use case for that then we should only handle the case where the GWs are provisioned for the first time, ie only deploy GWs `if len(currentGWInstanceList) == 0`. Otherwise I think it would be inconsistent if the increase case is handled but not the decrease case. I will say in the add-on, the `submarinerConfigController` that labels nodes as GWs does handle all cases tho I'm not sure how this relates to that.

 > If you think I should also check the zone, I can do it in a subsequent PR. Hope its fine with you.

Not sure what you mean by check the zone, but it seems to me the this code should use the same zone selection criteria as above and ensure we pick one that isn't already a GW. Perhaps we should compile an array of eligible zone names in the loop above in parallel with the `currentGWInstanceList` and loop over that list here?

2021-08-26 18:34 UTC, tpantelis requested changes

2021-08-26 18:34 UTC, tpantelis commented on pkg/gcp/gcp.go
> +	messageDeployGatewayNodeFailed = "Could not deploy the required number of Gateway nodes"
```suggestion
	messageInsufficientInstancesForDeploy = "There are insufficient zone instances to deploy the required number of gateways"
```

2021-08-26 18:34 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +			reporter.Succeeded(messageDeployGatewayNodeFailed)
It didn't technically succeed or may have partially succeeded. Perhaps this should this should call `Failed`? I'm not sure how the `Reporter` interface is/will be used by implementors.

2021-08-27 06:10 UTC, sridhargaddam reviewed
Thanks for reviewing @tpantelis. Addressed the review comments.

2021-08-27 06:10 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +			reporter.Succeeded(messageDeployGatewayNodeFailed)
Changed it to use messageDeployGatewayNodeFailed

2021-08-27 06:10 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +			err := d.deployGateway(zone.Name)
> hmm... but this is handling the increase case. If there's no use case for that then we should only handle the case where the GWs are provisioned for the first time, ie only deploy GWs `if len(currentGWInstanceList) == 0`. Otherwise I think it would be inconsistent if the increase case is handled but not the decrease case. 

Although we don't have an immediate use-case to support increasing the gateways, it will surely be helpful when the user wants to modify the cluster from a non-HA deployment (aka single GWNode) to an HA deployment (with multiple gateway nodes) without affecting the datapath. At the same time, we do not support decreasing the gateway count because it would affect the datapath connectivity as we might accidentally delete the active Gateway node in the cluster. Also JFYI, in OpenShift AFAIK it supports increasing the POD/SVC CIDR ranges but does not allow decreasing them.

> Not sure what you mean by check the zone, but it seems to me the this code should use the same zone selection criteria as above and ensure we pick one that isn't already a GW. Perhaps we should compile an array of eligible zone names in the loop above in parallel with the `currentGWInstanceList` and loop over that list here?

Done.

2021-08-27 13:37 UTC, tpantelis requested changes

2021-08-27 13:37 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +	zonesWithSubmarinerGW := stringset.NewSynchronized()
This doesn't need to be synchronized since it's used locally on a single thread.

2021-08-27 13:37 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +	if len(currentGWInstanceList) == input.Gateways {
`currentGWInstanceList` is now redundant with `zonesWithSubmarinerGW`

```suggestion
	if len(zonesWithSubmarinerGW) == input.Gateways {
```

2021-08-27 13:37 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +		gatewayNodesToDeploy := input.Gateways - len(currentGWInstanceList)
```suggestion
	if len(zonesWithSubmarinerGW) < input.Gateways {
		gatewayNodesToDeploy := input.Gateways - len(zonesWithSubmarinerGW)
```

2021-08-27 13:37 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +						}
Can 2 zones have the same name? If not you can just use an array. Either way you can just do `Add` w/o `Contains`.

```suggestion
						zonesWithSubmarinerGW.Contains(zone.Name)
```

2021-08-27 13:37 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +			if zonesWithSubmarinerGW.Contains(zone.Name) {
As mentioned in previous comments, we're still not using the same selection criteria here as above when compiling the list of existing GW zones.  So we could end up deploying on a zone whose region doesn't match `d.gcp.region` as per L84-85 above or doesn't have a public IP as per L101. I assume this would not be desired. Hence I suggest we build an `eligibleZones` list in parallel with `zonesWithSubmarinerGW`, ie if the zone has the `submarinerGatewayNodeTag` above (circa L102), gthen  add it to  `eligibleZones` and loop thru that here.

2021-08-27 13:37 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +			continue
We really don't need to check the region here since we'll only initiate the delete below if the `submarinerGatewayNodeTag` is present. Also we don't check for the public IP here as above on L102. I think it's simpler if keep the selection criteria in one place. This code need only check for the `submarinerGatewayNodeTag`.

2021-08-27 13:37 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +			reporter.Succeeded(messageInsufficientZonesForDeploy)
maybe a nit but should this be considered `Failed` from the reporter's standpoint?

2021-08-27 16:01 UTC, sridhargaddam reviewed
Addressed the review comments @tpantelis

2021-08-27 16:01 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +						}
No, two zones cannot have the same name. But a zone can have multiple instances in it.

2021-08-27 16:01 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +	if len(currentGWInstanceList) == input.Gateways {
I'm sure you meant zonesWithSubmarinerGW.Size() :)

2021-08-27 16:01 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +			continue
Basically, when we list the zones in a project, it will list all the available zones in all the regions. For example - https://paste.centos.org/view/e26eead1

The validation in line 250 helps us to avoid querying the instances in other regions. Please note that with the GCP Credentials we have, we can have multiple OCP clusters in different regions (each one is uniquely identified using the InfraID). For example, you can see that when I list the instances using my GCP Creds, I can see instances that belong to other users too - https://paste.centos.org/view/e6f41036

I'm modifying the code slightly to check if the instanceName contains the infraID

2021-08-27 16:01 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +			if zonesWithSubmarinerGW.Contains(zone.Name) {
Good point @tpantelis. I'm updating the code and also removing the additional check for publicIP, its sufficient if we just look for the `submarinerGatewayNodeTag` tag.

2021-08-27 17:32 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +			continue
OK so the redundant check here is for performance - makes sense. Perhaps we could put this upfront checking in an `ignoreZone` function.

2021-08-27 17:33 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +	if len(currentGWInstanceList) == input.Gateways {
yes 😄

2021-08-27 17:45 UTC, tpantelis requested changes

2021-08-27 17:45 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +			if strings.HasPrefix(instance.Name, prefix) {
So now this differs with the checking circa L95. I'm not clear on why this now checks the `instance.Name` but L95 doesn't and this no longer checks `submarinerGatewayNodeTag`. It seems we could now deploy a GW on an instance w/o the desired prefix and it won't get deleted. It seems we want this check before L95 and keep the `submarinerGatewayNodeTag` check as it was here.

2021-08-27 18:17 UTC, sridhargaddam reviewed
Done, updated @tpantelis

2021-08-27 18:17 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +			if strings.HasPrefix(instance.Name, prefix) {
Basically we have two use-cases
1. Deploying new GW Nodes using the OCPMachineSet API (this PR basically implements it)
2. Modifying one (or more) of the existing Worker nodes as Gateway Nodes - I'll push a separate PR once this PR is merged.

The code in L95 will be common to both of them, hence I'm using the check `submarinerGatewayNodeTag`. Let me remove it and use the same check in this PR.

2021-08-27 18:17 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +			continue
Done.

2021-08-27 21:20 UTC, tpantelis reviewed
Looks good. One more comment/question.

2021-08-27 21:20 UTC, tpantelis commented on pkg/gcp/ocpgwdeployer.go
> +			prefix := d.gcp.infraID + "-submariner-gw-" + zone.Name
So the search criteria here matches that of `Deploy` 👍 . So you've changed it to check the instance name instead of the `submarinerGatewayNodeTag`. What was the reason for this and what is the purpose now of the `submarinerGatewayNodeTag`?

2021-08-28 05:30 UTC, sridhargaddam commented on pkg/gcp/ocpgwdeployer.go
> +			prefix := d.gcp.infraID + "-submariner-gw-" + zone.Name
In this PR we are adding support for deploying new Dedicated Nodes as Submariner Gateway Nodes. These nodes are created with OCP Machineset API and are named in the following manner (file pkg/gcp/gw-machineset.go) Line 25
`name: {{.InfraID}}-submariner-gw-{{.AZ}}`

So, I'm now using the name itself as an identity while deleting the Gateways.

The `submarinerGatewayNodeTag` is basically used to ensure that ExternalFirewallRules (like `nattPort UDP/4500`, `natDiscoveryPort UDP/4490`, `esp` and `ah`) are applied only on Gateway instances with `targetTags` that include `submarinerGatewayNodeTag` and not to every instance in the cluster. You can see that while creating a new dedicated Gateway node we are explicitly setting the Tag in Line 78 (pkg/gcp/gw-machineset.go) and also while creating the ExternalFirewallRules using the same Tag Line 40 (pkg/gcp/firewall_rules.go). Hope its clear.

2021-08-28 11:51 UTC, tpantelis approved these changes

2021-08-30 07:11 UTC, aswinsuryan approved these changes

2021-08-30 08:25 UTC, vthapar approved these changes

2021-08-30 08:43 UTC, skitt requested changes
There are a lot of explanations of “why?” on various topics in response to the review comments in this PR; I think it would be extremely useful to have these preserved somewhere other than just the PR — either in comments in the code, or in the Submariner documentation (and if it is there already, sorry, I haven’t found it).

2021-08-30 14:57 UTC, sridhargaddam commented
> There are a lot of explanations of “why?” on various topics in response to the review comments in this PR; I think it would be extremely useful to have these preserved somewhere other than just the PR — either in comments in the code, or in the Submariner documentation (and if it is there already, sorry, I haven’t found it).

Done

2021-08-30 14:58 UTC, sridhargaddam commented
Note: Feel free to Squash the individual commits before merging.

2021-08-31 08:23 UTC, skitt approved these changes
Fantastic, thanks @sridhargaddam!

2021-08-31 08:23 UTC, merged